"""empty message

Revision ID: 20aeafa0497e
Revises: 
Create Date: 2021-11-11 01:31:44.265785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20aeafa0497e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein_range',
    sa.Column('protein_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protein_name', sa.Text(), nullable=True),
    sa.Column('protein_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('protein_index')
    )
    op.create_table('product',
    sa.Column('product_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.Text(length=150), nullable=True),
    sa.Column('product_tag', sa.Text(), nullable=True),
    sa.Column('product_kcal', sa.Float(), nullable=True),
    sa.Column('product_protein', sa.Float(), nullable=True),
    sa.Column('product_Na', sa.Float(), nullable=True),
    sa.Column('product_Ka', sa.Float(), nullable=True),
    sa.Column('product_p', sa.Float(), nullable=True),
    sa.Column('product_carbohydrate', sa.Float(), nullable=True),
    sa.Column('product_protein_range', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_protein_range'], ['protein_range.protein_index'], ),
    sa.PrimaryKeyConstraint('product_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('protein_range')
    # ### end Alembic commands ###
