"""empty message

Revision ID: 2fac2bb80c01
Revises: 
Create Date: 2021-12-04 00:39:27.679936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fac2bb80c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('memberId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.Text(length=100), nullable=True),
    sa.Column('Sex', sa.Text(length=10), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('phoneNumber', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.create_table('protein',
    sa.Column('proteinId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proteinName', sa.Text(), nullable=True),
    sa.Column('proteinDesc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('proteinId')
    )
    op.create_table('test_user',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LineId', sa.Text(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('bloodpressure',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('bpId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sp', sa.Float(), nullable=True),
    sa.Column('dp', sa.Float(), nullable=True),
    sa.Column('mbp', sa.Float(), nullable=True),
    sa.Column('createDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('bpId')
    )
    op.create_table('bloodsugar',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('bsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sugarValue', sa.Float(), nullable=True),
    sa.Column('createDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('bsId')
    )
    op.create_table('diseasetype',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('diseaseId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typeName', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('diseaseId')
    )
    op.create_table('food',
    sa.Column('foodId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foodName', sa.Text(length=150), nullable=True),
    sa.Column('foodTag', sa.Text(), nullable=True),
    sa.Column('foodKcal', sa.Float(), nullable=True),
    sa.Column('foodProtein', sa.Float(), nullable=True),
    sa.Column('foodNaa', sa.Float(), nullable=True),
    sa.Column('foodKa', sa.Float(), nullable=True),
    sa.Column('foodP', sa.Float(), nullable=True),
    sa.Column('foodCarbohydrate', sa.Float(), nullable=True),
    sa.Column('foodProteinId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foodProteinId'], ['protein.proteinId'], ),
    sa.PrimaryKeyConstraint('foodId')
    )
    op.create_table('post',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('postId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imgSrc', sa.Text(), nullable=True),
    sa.Column('postTitle', sa.Text(), nullable=True),
    sa.Column('postLike', sa.Boolean(), nullable=True),
    sa.Column('createDateTime', sa.DateTime(), nullable=True),
    sa.Column('updateDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('postId')
    )
    op.create_table('message',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('messageId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('messageContent', sa.Text(), nullable=True),
    sa.Column('messageLike', sa.Boolean(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.ForeignKeyConstraint(['postId'], ['post.postId'], ),
    sa.PrimaryKeyConstraint('messageId')
    )
    op.create_table('whoLikes',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.memberId'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.postId'], ),
    sa.PrimaryKeyConstraint('member_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whoLikes')
    op.drop_table('message')
    op.drop_table('post')
    op.drop_table('food')
    op.drop_table('diseasetype')
    op.drop_table('bloodsugar')
    op.drop_table('bloodpressure')
    op.drop_table('test_user')
    op.drop_table('protein')
    op.drop_table('member')
    # ### end Alembic commands ###
