"""'創建資料表'

Revision ID: 9074561f0b87
Revises: 
Create Date: 2021-11-15 23:18:00.336818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9074561f0b87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('memberId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.Text(length=100), nullable=True),
    sa.Column('Sex', sa.Text(length=10), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('phoneNumber', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.create_table('protein',
    sa.Column('proteinId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proteinName', sa.Text(), nullable=True),
    sa.Column('proteinDesc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('proteinId')
    )
    op.create_table('bloodpressure',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('bpId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sp', sa.Float(), nullable=True),
    sa.Column('dp', sa.Float(), nullable=True),
    sa.Column('mbp', sa.Float(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('bpId')
    )
    op.create_table('bloodsugar',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('bsId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sugarValue', sa.Float(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('bsId')
    )
    op.create_table('diseasetype',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('diseaseId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typeName', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('diseaseId')
    )
    op.create_table('food',
    sa.Column('foodId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foodName', sa.Text(length=150), nullable=True),
    sa.Column('foodTag', sa.Text(), nullable=True),
    sa.Column('foodKcal', sa.Float(), nullable=True),
    sa.Column('foodProtein', sa.Float(), nullable=True),
    sa.Column('foodNaa', sa.Float(), nullable=True),
    sa.Column('foodKa', sa.Float(), nullable=True),
    sa.Column('foodP', sa.Float(), nullable=True),
    sa.Column('foodCarbohydrate', sa.Float(), nullable=True),
    sa.Column('foodProteinId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foodProteinId'], ['protein.proteinId'], ),
    sa.PrimaryKeyConstraint('foodId')
    )
    op.create_table('post',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('postId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imgSrc', sa.Text(), nullable=True),
    sa.Column('postTitle', sa.Text(), nullable=True),
    sa.Column('postLike', sa.Boolean(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.PrimaryKeyConstraint('postId')
    )
    op.create_table('message',
    sa.Column('memberId', sa.Integer(), nullable=True),
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('messageId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('messageContent', sa.Text(), nullable=True),
    sa.Column('messageLike', sa.Boolean(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.memberId'], ),
    sa.ForeignKeyConstraint(['postId'], ['post.postId'], ),
    sa.PrimaryKeyConstraint('messageId')
    )
    op.drop_table('product')
    op.drop_table('protein_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protein_range',
    sa.Column('protein_index', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('protein_name', mysql.TEXT(), nullable=True),
    sa.Column('protein_desc', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('protein_index'),
    mysql_default_charset='big5',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('product_index', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.TEXT(), nullable=True),
    sa.Column('product_tag', mysql.TEXT(), nullable=True),
    sa.Column('product_kcal', mysql.FLOAT(), nullable=True),
    sa.Column('product_protein', mysql.FLOAT(), nullable=True),
    sa.Column('product_Na', mysql.FLOAT(), nullable=True),
    sa.Column('product_Ka', mysql.FLOAT(), nullable=True),
    sa.Column('product_p', mysql.FLOAT(), nullable=True),
    sa.Column('product_carbohydrate', mysql.FLOAT(), nullable=True),
    sa.Column('product_protein_range', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_protein_range'], ['protein_range.protein_index'], name='product_ibfk_1'),
    sa.PrimaryKeyConstraint('product_index'),
    mysql_default_charset='big5',
    mysql_engine='InnoDB'
    )
    op.drop_table('message')
    op.drop_table('post')
    op.drop_table('food')
    op.drop_table('diseasetype')
    op.drop_table('bloodsugar')
    op.drop_table('bloodpressure')
    op.drop_table('protein')
    op.drop_table('member')
    # ### end Alembic commands ###
